- name: Install python3
  yum:
    name: python3
    state: present

- name: Install docker with python 3
  pip:
    name: docker
    executable: pip3

- name: Front Startup
  docker_container:
    name: frontend-container
    image: davijea/front:1.0
    recreate: true
    state: started
    ports:
      - "80:80"
    env: 
      VUE_APP_API_URL: "david.jeannin.takima.cloud:8080"
  vars:
    ansible_python_interpreter: /usr/bin/python3
