- name: Pull Docker image
  docker_image:
    name: davijea/api
    tag: 1.0
    source: pull
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Run api Docker container
  docker_container:
    name: david-api
    image: davijea/api:1.0
    recreate: true
    state: started
    env:
      POSTGRES_PASSWORD: "davidpg"
      POSTGRES_USER: "davidpg"
      POSTGRES_URL: "david-pg:5432"
      POSTGRES_DB: "davidpg"
    network_mode: "app-network"
  vars:
    ansible_python_interpreter: /usr/bin/python3


