- name: Pull Docker image
  docker_image:
    name: davijea/test
    tag: 1.0
    source: pull
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Run api Docker container
  docker_container:
    name: api-container
    image: davijea/test:1.0
    state: started
    env:
      POSTGRES_PASSWORD: "david"
      POSTGRES_USER: "david"
      POSTGRES_URL: "david-pg:5432"
      POSTGRES_DB: "davidpg"
    network_mode: "app-network"
  vars:
    ansible_python_interpreter: /usr/bin/python3


