all:
 vars:
   ansible_user: "{{ ansible_user }}"
   ansible_ssh_private_key_file: "{{ ansible_key }}"
   postgres_password: "davidpg"
   postgres_user: "davidpg"
   postgres_db: "davidpg"
   postgres_url: "davidpg-5432"
 children:
   prod:
     hosts:
      "{{ ansible_host }}"
