- name: Create directory
  file:
    path: /home/centos/bdd
    state: directory

- name: Pull Docker image
  docker_image:
    name: davijea/postgres
    tag: 1.0
    source: pull
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Run Docker container
  docker_container:
    name: david-pg
    image: davijea/postgres
    state: started
    volumes:
      - "/home/centos/bdd:/var/lib/postgresql/data"
    env:
      POSTGRES_PASSWORD: "davidpg"
      POSTGRES_USER: "davidpg"
      POSTGRES_DB: "davidpg"
    network_mode: "app-network"
  vars:
    ansible_python_interpreter: /usr/bin/python3
