name: CI deployement

on:
  workflow_run:
    workflows:
      - "Build and Push Docker Image CI"
    types:
        - completed
    branches:
        - main
jobs:
  deployement:
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-22.04
    steps:
      #checkout your github code using actions/checkout@v2.5.0
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      #run ansible playbook to deploy the backend.
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
            playbook: playbook.yml
            key: ${{secrets.SSH_KEY}}
            directory: ansible
            inventory: |
              [all]
              david.jeannin.takima.cloud
            vault_password: ${{secrets.VAULT_PWD}}
            options: |
              -u centos